### ISSUE TITLE
Error opening database

### ISSUE THREAD

**Issue by liuxp2000** [nthjelme/nodejs-domino#11]
var Domino = require('domino-nsf');
var domino = Domino();
 
var doc = {
  "FullName":"John Smith",
  "tags":["test","test2"],
  "age":33,
  "Form":"Person"
};
 
var db = domino.use({server:"yesme",database:"TWDemo.nsf"});
//let db = domino.openDatabase('TWDemo.nsf');

db.insert(doc,function(error,document) {
    // returns the saved document
    console.log("document",document);
});

 
domino.termSession(); 

<img width="1112" alt="2018-09-17 10 27 46" src="https://user-images.githubusercontent.com/37297613/45629411-f87d8000-bac8-11e8-85ab-af79ea439787.png">

**Comment by nthjelme** [comment]
the db.insert callback funtion is async, so the result of you code would be that you are terminating the session before it finishes saving the document.

try to call the termSession in the callback function like this:

```
db.insert(doc,function(error,document) {
  console.log("document",document);
  domino.termSession();
});
```

**Comment by liuxp2000** [comment]
The function domino.use() can not open the database. I've tried:
var db = domino.use({server:'yesme/wwcorp',database:'TWDemo.nsf'});
var db = domino.use({server:'',database:'TWDemo.nsf'});   (I've created a copy in local)
var db = domino.use({server:'192.168.1.10',database:'TWDemo.nsf'});
All result  "error opening database"

If I use: var db = domino.openDatabase('yesme!!TWDemo.nsf'), 
it works, but when call doc.insert(), it report  insert is not a function.

**Comment by liuxp2000** [comment]
Hi Nils,
After change to this:
db.insert(doc,function(error,document) {
  console.log("document",document);
  domino.termSession();
});

It works. but It only insert document into the local nsf, instead of server side nsf. whatever server name I used.

**Comment by nthjelme** [comment]
The sync API has some has some issues when connecting to a server, it only works locally.
I haven't had time to properly debug that...


The async should be able to connect to a server, or at least it does in my setup...

Can you try this? 

```
var domino = require('domino-nsf')(); 

var db = domino.use({database:'yesme/wwcorp!!TWDemo.nsf'});

db.insert({"Form":"Test","Subject":"hello from node.js!"},function(err,doc) {
  if(err) {
    console.log("err",err)
  }
  console.log("doc",doc);
  domino.termSession();  
})
```

**Comment by liuxp2000** [comment]
Cool! It works. And the sync API can connect to server too. 
Thanks a lot!

**Comment by nthjelme** [comment]
Good to hear it worked out for you :)
