### ISSUE TITLE
Create build scripts for win64 and linux

### ISSUE THREAD

**Issue by nthjelme** [nthjelme/nodejs-domino#2]

**Comment by cristiandley** [comment]
What is this package missing to work on linux ?

**Comment by nthjelme** [comment]
It will only work on 32-bit Linux, as the IBM Notes C++ API (which the nodejs-domino is using) only comes with prebuilt 32-bit libs for Linux.

I guess you can build it on 64-bit Linux if you install the 32-bit build tools/gcc and libs and build it against the 32-bit Notes client.

You would also need to add a condition OS=="linux" to the bindings.gyp file, with the correct compiler flags,libraries, etc. 

Because of that, and the C++ API isn't supported by IBM anymore, I'm planning to rewrite the implementations against the supported C API. It would then be possible to target 64-bit Linux.

I would be very happy if anyone would like to help out with the rewrite.. :)

**Comment by cristiandley** [comment]
@nthjelme okey i will start doing some PR's under "linux" branch

or what name should i use ?

**Comment by nthjelme** [comment]
"linux" if fine :)

I did play around with building on linux a while back, here is the [binding.gyp](https://gist.github.com/nthjelme/6a6c40fcc4d370b402cbd3d74c01ddab) I used. Hopefully it'll give you a little head start..

**Comment by nthjelme** [comment]
It does now build and run under linux, it's only been tested in ubuntu 14.04 running iin a docker container

.
